# Generated by Django 4.2.1 on 2023-05-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AfterPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("pseudonym", models.CharField(max_length=50)),
                ("photo", models.ImageField(upload_to="after_photos")),
            ],
        ),
        migrations.CreateModel(
            name="BeforePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("pseudonym", models.CharField(max_length=50)),
                ("photo", models.ImageField(upload_to="before_photos")),
            ],
        ),
    ]
