# Generated by Django 4.2.1 on 2023-05-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("then_and_now_project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beforephoto",
            name="pseudonym",
            field=models.CharField(max_length=100),
        ),
    ]
